// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from '@tauri-apps/api/core';
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	killSidecar: () => __TAURI_INVOKE<void>("kill_sidecar"),
	readThirdPartyNotices: () => __TAURI_INVOKE<string>("read_third_party_notices"),
	readLicense: () => __TAURI_INVOKE<string>("read_license"),
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
	readGpdKey: () => __TAURI_INVOKE<string | null>("read_gpd_key"),
	removeGpdKey: () => __TAURI_INVOKE<null>("remove_gpd_key"),
	readProfile: () => __TAURI_INVOKE<string | null>("read_profile"),
	writeProfile: (json: string) => __TAURI_INVOKE<null>("write_profile", { json }),
	installCli: () => __TAURI_INVOKE<string>("install_cli"),
	awaitInitialization: (events: Channel) => __TAURI_INVOKE<ServerReadyData>("await_initialization", { events }),
	getDefaultServerUrl: () => __TAURI_INVOKE<string | null>("get_default_server_url"),
	setDefaultServerUrl: (url: string | null) => __TAURI_INVOKE<null>("set_default_server_url", { url }),
	getWslConfig: () => __TAURI_INVOKE<WslConfig>("get_wsl_config"),
	setWslConfig: (config: WslConfig) => __TAURI_INVOKE<null>("set_wsl_config", { config }),
	getDisplayBackend: () => __TAURI_INVOKE<"wayland" | "auto" | null>("get_display_backend"),
	setDisplayBackend: (backend: LinuxDisplayBackend) => __TAURI_INVOKE<null>("set_display_backend", { backend }),
	parseMarkdownCommand: (markdown: string) => __TAURI_INVOKE<string>("parse_markdown_command", { markdown }),
	checkAppExists: (appName: string) => __TAURI_INVOKE<boolean>("check_app_exists", { appName }),
	wslPath: (path: string, mode: "windows" | "linux" | null) => __TAURI_INVOKE<string>("wsl_path", { path, mode }),
	resolveAppPath: (appName: string) => __TAURI_INVOKE<string | null>("resolve_app_path", { appName }),
	openPath: (path: string, appName: string | null) => __TAURI_INVOKE<null>("open_path", { path, appName }),
	installGitMacos: () => __TAURI_INVOKE<InstallResult>("install_git_macos"),
	installGitWindows: () => __TAURI_INVOKE<InstallResult>("install_git_windows"),
	linuxInstallHint: (tool: string) => __TAURI_INVOKE<string>("linux_install_hint", { tool }),
	repairGpdVenv: () => __TAURI_INVOKE<null>("repair_gpd_venv"),
	installTectonic: () => __TAURI_INVOKE<string>("install_tectonic"),
	detectTexCompiler: () => __TAURI_INVOKE<TexCompilerInfo>("detect_tex_compiler"),
	detectTexRoot: (startFile: string) => __TAURI_INVOKE<string>("detect_tex_root", { startFile }),
	compileTex: (projectId: string, texFile: string, rootFile: string | null) => __TAURI_INVOKE<TexCompileResult>("compile_tex", { projectId, texFile, rootFile }),
	synctexForward: (synctexPath: string, page: number, x: number, y: number) => __TAURI_INVOKE<SyncTexResult>("synctex_forward", { synctexPath, page, x, y }),
	synctexReverse: (synctexPath: string, sourceFile: string, line: number) => __TAURI_INVOKE<SyncTexResult>("synctex_reverse", { synctexPath, sourceFile, line }),
	parseTexLog: (logPath: string) => __TAURI_INVOKE<TexLogParseResult>("parse_tex_log", { logPath }),
	readTexArtifactBase64: (path: string) => __TAURI_INVOKE<string>("read_tex_artifact_base64", { path }),
	saveTexArtifactToPath: (src: string, dest: string) => __TAURI_INVOKE<null>("save_tex_artifact_to_path", { src, dest }),
	createProjectDirectory: (parent: string, name: string) => __TAURI_INVOKE<string>("create_project_directory", { parent, name }),
	checkProjectAccessible: (path: string) => __TAURI_INVOKE<string>("check_project_accessible", { path }),
	canonicalizeProjectPath: (path: string) => __TAURI_INVOKE<string>("canonicalize_project_path", { path }),
};

/** Events */
export const events = {
	gpdFirstRunComplete: makeEvent<GpdFirstRunComplete>("gpd-first-run-complete"),
	loadingWindowComplete: makeEvent<LoadingWindowComplete>("loading-window-complete"),
	sqliteMigrationProgress: makeEvent<SqliteMigrationProgress>("sqlite-migration-progress"),
	tectonicDownloadProgress: makeEvent<TectonicDownloadProgress>("tectonic-download-progress"),
	texCompileProgress: makeEvent<TexCompileProgress>("tex-compile-progress"),
};

/* Types */
/**
 * Emitted once, after a successful GPD first-run setup, so the frontend can
 * show an informational toast about where files were installed.
 */
export type GpdFirstRunComplete = null;

export type InitStep = { phase: "server_waiting" } | { phase: "sqlite_waiting" } | { phase: "gpd_setup" } | { phase: "done" };

/**
 * Result returned to the frontend after an install command is spawned.
 */
export type InstallResult = {
		
	/**
 * Whether the installer was launched successfully. This does not
 * guarantee the install finished — some installers detach and run
 * out-of-band (e.g. xcode-select's GUI prompt).
 */
launched: boolean,
		
	/**
 * Human-readable message describing what happened.
 */
message: string,
	};

export type LinuxDisplayBackend = "wayland" | "auto";

export type LoadingWindowComplete = null;

export type ServerReadyData = {
		url: string,
		username: string | null,
		password: string | null,
	};

export type SqliteMigrationProgress = { type: "InProgress"; value: number } | { type: "Done" };

export type SyncTexResult = {
		
	/**
 * For forward (PDF → source): the resolved source file.
 */
file: string | null,
		line: number | null,
		
	/**
 * For reverse (source → PDF): page and fractional coordinates (points).
 */
page: number | null,
		x: number | null,
		y: number | null,
	};

/**
 * Progress payload emitted under the `tectonic-download-progress` event
 * while the Tectonic archive is being streamed from GitHub.
 * 
 * Fields are typed as `f64` (rather than `u64`) because TypeScript's
 * `number` is a double and the specta TypeScript exporter forbids
 * `BigInt`-backed integers by default. Tectonic archives are ~20-30 MB,
 * which is well inside the safe-integer range for `f64`.
 */
export type TectonicDownloadProgress = {
		
	/**
 * Bytes downloaded so far.
 */
loaded: number,
		
	/**
 * Total bytes advertised by the server, or 0 if unknown.
 */
total: number,
	};

/**
 * Progress event emitted while a compile is running so the Build pane can
 * show a spinner with a human-readable phase.
 */
export type TexCompileProgress = {
		
	/**
 * One of: "starting", "running", "bibbing", "finalizing", "done", "error".
 */
status: string,
		
	/**
 * 0-100, best-effort. We don't parse log byte counts — this is a coarse
 * estimate derived from the phase so the progress bar at least moves.
 */
percent: number,
		
	/**
 * Short translated-by-frontend message ID or prose describing the phase.
 */
message: string,
	};

export type TexCompileResult = {
		status: TexCompileStatus,
		
	/**
 * Absolute path to the produced PDF, if any.
 */
pdfPath: string | null,
		
	/**
 * Absolute path to the `.synctex.gz` file, if any.
 */
synctexPath: string | null,
		
	/**
 * Absolute path to the `.log` file, if any.
 */
logPath: string | null,
		
	/**
 * Which compiler was used.
 */
compilerKind: string | null,
		compilerPath: string | null,
		
	/**
 * Wall-clock duration of the compile in milliseconds.
 */
durationMs: number,
		errors: TexDiagnostic[],
		warnings: TexDiagnostic[],
		
	/**
 * The `.tex` file that was actually used as the root.
 */
rootFile: string,
		
	/**
 * The output directory used (under the GPD cache).
 */
outDir: string,
	};

export type TexCompileStatus = 
	/**
 * Compile exit 0, PDF exists.
 */
"success" | 
	/**
 * Compile produced a PDF despite warnings or non-fatal errors.
 */
"success_with_warnings" | 
	/**
 * Compile failed — no PDF, or PDF missing after run.
 */
"error" | 
	/**
 * No compiler found on the system. UI should show install CTA.
 */
"no_compiler" | 
	/**
 * User cancelled an in-flight compile.
 */
"cancelled";

export type TexCompilerInfo = {
		kind: string,
		path: string | null,
		
	/**
 * True iff `latexmk` was also found on PATH — we prefer it when
 * available because it handles the bib/glossary multi-pass dance.
 */
hasLatexmk: boolean,
		
	/**
 * True iff `bibtex` is on PATH (or bundled with the resolved compiler).
 */
hasBibtex: boolean,
		
	/**
 * True iff the `synctex` CLI is on PATH. Without it, we cannot support
 * bidirectional navigation even if `.synctex.gz` was generated.
 */
hasSynctex: boolean,
	};

export type TexDiagnostic = {
		severity: string,
		file: string | null,
		line: number | null,
		message: string,
	};

export type TexLogParseResult = {
		errors: TexDiagnostic[],
		warnings: TexDiagnostic[],
		rawLog: string,
	};

export type WslConfig = {
		enabled: boolean,
	};

export type WslPathMode = "windows" | "linux";

/* Tauri Specta runtime */
function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: (payload: T) => __TAURI_EVENT.emit(name, payload) as unknown as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: (payload: T) => target.emit(name, payload) as unknown as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

